/* Which brand saw the most dollars spent in the month of June? */
SELECT BRAND_CODE, ROUND(SUM(TOTAL_FINAL_PRICE),2) as TOTAL_SPENT
FROM RECEIPT_ITEMS
WHERE MONTH(STR_TO_DATE(MODIFY_DATE, '%Y-%m-%dT%H:%i:%s.%fZ')) = 6 AND BRAND_CODE IS NOT NULL AND BRAND_CODE not like ''
GROUP BY BRAND_CODE
ORDER BY TOTAL_SPENT desc
LIMIT 10;

/* Which user spent the most money in the month of August? */
SELECT USER_ID, ROUND(SUM(TOTAL_SPENT),2) as MONEY_SPENT
FROM RECEIPTS 
WHERE MONTH(STR_TO_DATE(MODIFY_DATE, '%Y-%m-%dT%H:%i:%s.%fZ')) = 8
GROUP BY USER_ID
ORDER BY MONEY_SPENT DESC
LIMIT 10;

/* What user bought the most expensive item? */
WITH MAX_PRICE AS (SELECT REWARDS_RECEIPT_ID, DESCRIPTION, BRAND_CODE,TOTAL_FINAL_PRICE FROM RECEIPT_ITEMS WHERE TOTAL_FINAL_PRICE = (SELECT MAX(TOTAL_FINAL_PRICE) FROM RECEIPT_ITEMS WHERE QUANTITY_PURCHASED>0))
SELECT r.USER_ID,mp.REWARDS_RECEIPT_ID, mp.TOTAL_FINAL_PRICE, mp.BRAND_CODE, DESCRIPTION FROM MAX_PRICE mp INNER JOIN receipts r ON mp.REWARDS_RECEIPT_ID = r.ID;

/* What is the name of the most expensive item purchased? */
SELECT REWARDS_RECEIPT_ID, DESCRIPTION, BRAND_CODE,TOTAL_FINAL_PRICE FROM RECEIPT_ITEMS WHERE TOTAL_FINAL_PRICE = (SELECT MAX(TOTAL_FINAL_PRICE) FROM RECEIPT_ITEMS WHERE QUANTITY_PURCHASED>0);

/* How many users scanned in each month? */
SELECT MONTH(STR_TO_DATE(DATE_SCANNED, '%Y-%m-%dT%H:%i:%s.%fZ')) AS MONTH_NUMBER, COUNT(DISTINCT USER_ID) AS USER_COUNT
FROM RECEIPTS
WHERE MONTH(STR_TO_DATE(DATE_SCANNED, '%Y-%m-%dT%H:%i:%s.%fZ')) IS NOT NULL
GROUP BY MONTH(STR_TO_DATE(DATE_SCANNED, '%Y-%m-%dT%H:%i:%s.%fZ'))
ORDER BY MONTH(STR_TO_DATE(DATE_SCANNED, '%Y-%m-%dT%H:%i:%s.%fZ'));
